# Generated by Django 5.2.4 on 2025-09-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('custom_amount', 'Custom Amount'), ('custom_percent', 'Custom Percent')], default='equal', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
