# Generated by Django 5.2.4 on 2025-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_split_type_alter_bill_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splithistory',
            name='action',
            field=models.CharField(choices=[('created', 'Bill Created'), ('approval', 'Approval'), ('debit', 'Wallet Debit'), ('paid', 'Marked as Paid'), ('decline', 'Decline')], default='created', max_length=20),
        ),
    ]
