# Generated by Django 5.2.4 on 2025-09-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_recurringbill_recurringbillparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbillparticipant',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=12),
            preserve_default=False,
        ),
    ]
