# Generated by Django 5.2.4 on 2025-09-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_recurringbillparticipant_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringbill',
            name='bill',
        ),
        migrations.AddField(
            model_name='recurringbill',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('custom_amount', 'Custom Amount'), ('custom_percent', 'Custom Percent')], default='equal', max_length=20),
        ),
    ]
