# Generated by Django 5.2.4 on 2025-09-13 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_remove_recurringbill_bill_recurringbill_split_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringbill',
            name='split_type',
        ),
        migrations.AddField(
            model_name='recurringbill',
            name='bill',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recurring_bills',
                to='bill.bill',
                null=True,  # allow NULL initially
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
