# Generated by Django 5.2.4 on 2025-09-13 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_remove_recurringbill_split_type_recurringbill_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringbill',
            name='participants',
        ),
    ]
