# Generated by Django 5.2.4 on 2025-09-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_remove_recurringbill_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbillparticipant',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurringbillparticipant',
            name='missed_cycles',
            field=models.PositiveIntegerField(default=0, help_text='How many billing cycles this user has missed'),
        ),
    ]
