# Generated by Django 5.2.4 on 2025-08-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
