# Generated by Django 5.2.4 on 2025-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.IntegerField(blank=True, max_length=6, null=True, verbose_name='OTP'),
        ),
    ]
