# Generated by Django 5.2.4 on 2025-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(default='', verbose_name='PIN'),
        ),
    ]
