# Generated by Django 5.2.4 on 2025-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_token',
            field=models.CharField(max_length=255, verbose_name='Device Code'),
        ),
    ]
