# Generated by Django 5.2.4 on 2025-09-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_groups_friends_groupmembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='GroupMember',
        ),
    ]
