# Generated by Django 5.2.4 on 2025-09-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_friends_friend_rename_groups_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friends',
            new_name='friend',
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user', 'friend')},
        ),
    ]
