# Generated by Django 5.2.4 on 2025-09-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Group Name'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'creator')},
        ),
    ]
